#include <Gnome.idl>

module Foo {

    module Test {
	
	struct Simple {
	    GNOME::LocalizedStringList Ignore;
	    short a;
	    long b;
	};

    };

    module Desktop {

	enum EntryType {
	    ENTRY_TYPE_UNKNOWN,
	    ENTRY_TYPE_APPLICATION,
	    ENTRY_TYPE_URL,
	    ENTRY_TYPE_LINK,
	    ENTRY_TYPE_FSDEVICE,
	    ENTRY_TYPE_MIMETYPE,
	    ENTRY_TYPE_DIRECTORY,
	    ENTRY_TYPE_SERVICE,
	    ENTRY_TYPE_SERVICETYPE,
	    ENTRY_TYPE_PANEL_APPLET,
	    ENTRY_TYPE_SEPARATOR
	};

	struct Entry {
	    GNOME::Encoding Encoding;
	    GNOME::LocalizedStringList Name;
	    GNOME::LocalizedStringList Comment;
	    string Icon;
	    string Exec;
	    string TryExec;
	    string URL;
	    GNOME::stringlist SortOrder;
	    GNOME::ExtraAttributes Attributes;
	    EntryType Type;
	    boolean Terminal;
	};

    };
};
