#ifndef _GNOME_IDL_INCLUDED_
#define _GNOME_IDL_INCLUDED_

#if !defined(__GNOME_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs gnome/Gnome.h
%}
#pragma inhibit push
#endif

module GNOME {

    typedef sequence<string> stringlist;

};

#include <Gnome_Desktop.idl>

#if !defined(__GNOME_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif /* _GNOME_IDL_INCLUDED_ */
