#ifndef _GNOME_IDL_INCLUDED_
#define _GNOME_IDL_INCLUDED_

#include <Bonobo.idl>

#if !defined(__GNOME_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs libgnome/Gnome.h
%}
#pragma inhibit push
#endif

module GNOME {

    typedef sequence<string> stringlist;

    enum Tristate {
	TRISTATE_DEFAULT,
	TRISTATE_NO,
	TRISTATE_YES
    };

    struct LocalizedString {
	string locale;
	string text;
    };

    typedef sequence<LocalizedString> LocalizedStringList;

    typedef Bonobo::PropertySet ExtraAttributes;

    enum Encoding {
	ENCODING_NONE,
	ENCODING_UNKNOWN,
	ENCODING_UTF8,
	ENCODING_LEGACY_MIXED
    };

};

#if !defined(__GNOME_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif /* _GNOME_IDL_INCLUDED_ */
